drupaldb:
  image: bnchdrff/mariadb
  volumes_from:
    - drupal-db-data

drupalwww:
  build: ./nginx-php5-drupal
  volumes_from:
    - drupal-www-data
  links:
    - "ambassador:db"

ambassador:
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: "-name dockercomposedrupal_drupaldb_1 -name dockercomposedrupal_drupalwww_1"

nginxproxy:
  build: ./nginx-proxy
  links:
    - "ambassador:drupal-www"
  ports:
    - "80:80"
    - "443:443"
